<div class="jarviswidget">
	<header>
		<a class="btn btn-success" style="float: right;" href="/admin/onenews/"><i class="fa fa-plus"></i> Новая новость</i></a>
	</header>
	<div>
		<div class="widget-body no-padding">

			<div class="widget-body-toolbar">

			</div>

			<table id="dt_basic" class="table table-striped table-bordered table-hover">
				<thead>
				<tr>
					<th></th>
					<th>Название</th>
					<th>Статус</th>
					<th>Начало</th>
					<th>Конец</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach ($this->items as $item ) {?>
					<tr>
						<td>
							<a class="btn btn-default btn-circle" title="Редактировать" href="/admin/onenews/id/<?=$item->getId()?>">
								<i class="glyphicon glyphicon-pencil"></i>
							</a>
							<a class="btn btn-default btn-circle" title="Просмотр" target="_blank"
							   	href="<?=$item->getPath()?>">
								<i class="glyphicon glyphicon-eye-open"></i>
							</a>
							<a class="btn btn-warning btn-circle" title="Удалить" href="/admin/news/delete/<?=$item->getId()?>"
								 onclick="return confirm('Вы уверены что хотите удалить ?')">
								<i class="glyphicon glyphicon-remove"></i>
							</a>

						</td>
						<td><?=$item->getTitle()?></td>
						<td><?=$item->getStatusText()?></td>
						<td><?=$item->getStart()?date('d.m.Y',strtotime($item->getStart())):''?></td>
						<td><?=$item->getEnd()?date('d.m.Y',strtotime($item->getEnd())):''?></td>
					</tr>
				<?php }	?>
				</tbody>
			</table>

		</div>
	</div>
</div>


<script src="/admin_template/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ColReorder.min.js"></script>
<script src="/admin_template/js/plugin/datatables/FixedColumns.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ColVis.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ZeroClipboard.js"></script>
<script src="/admin_template/js/plugin/datatables/media/js/TableTools.min.js"></script>
<script src="/admin_template/js/plugin/datatables/DT_bootstrap.js"></script>

<script type="text/javascript">
	$(document).ready(function () {

		$('#dt_basic').dataTable({
			"sPaginationType": "bootstrap_full"
		});

	});
</script>