<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
	<meta content="ru-RU" http-equiv="Content-Language">
	<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.css"/>
	<link rel="stylesheet" href="/bootstrap/css/bootstrap_ui.css"/>
</head>
<body>
<header id="top">

	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">Tools</a>
			</div>


			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="<?php if($this->get->controller == 'Wm') echo 'active';?> dropdown">
						<a href="/wm/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Wm <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="/wm/">Send</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="/wm/status/">Transaction Status</a></li>
							<li><a href="/wm/history/">History</a></li>
							<li><a href="/wm/refund/">Refund</a></li>
							<li><a href="/wm/receipt/">Receipt</a></li>
							<li><a href="/wm/bankpayments/">Bank payments</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</nav>

</header>
<div class="container">
	<div class="row">
		<h1 class="page-header"><?= $this->pageName ?></h1>

		<?php if(count($this->messageInfo)) { ?>
			<div class="alert alert-info" role="alert">
				<?php foreach($this->messageInfo as $message) { ?>
					<h4><?=$message?></h4>
				<?php } ?>
			</div>
		<?php }?>

		<?php if(count($this->messageError)) { ?>
			<div class="alert alert-danger" role="alert">
				<?php foreach($this->messageError as $message) { ?>
					<h4><?=$message?></h4>
				<?php } ?>
			</div>
		<?php }?>

		<?php echo $this->layout()->content; ?>
	</div>
</div>

<script src="/js/jquery.1.11.3.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>
<script src="/admin_template/js/libs/jquery-ui-1.10.3.min.js"></script>

<script>
	$(document).ready(function () {
		$('.datepicker').datepicker({
			dateFormat: 'yy-mm-dd',
			maxDate: '+0d'
		});

	});
</script>
</body>
</html>