<div class="col-md-4">
	<form method="post" action="">
		<div class="form-group">
			<label for="DateFrom">DateFrom</label>
			<input type="text" class="form-control datepicker" name="DateFrom" id="DateFrom" >
		</div>
		<div class="form-group">
			<label for="DateTo">DateTo</label>
			<input type="text" class="form-control datepicker" value="<?=date('Y-m-d')?>" name="DateTo" id="DateTo" >
		</div>

		<button class="btn btn-default" type="submit">Submit</button>
	</form>
</div>
<div class="col-md-4">
	<?php if($this->info) d($this->info, false);?>
</div>