<div class="col-md-4">
	<form method="post" action="">
		<div class="form-group">
			<label for="LMI_PAYMENT_AMOUNT">Amount *</label>
			<input type="text" class="form-control" name="LMI_PAYMENT_AMOUNT" id="LMI_PAYMENT_AMOUNT" placeholder="0.00">
		</div>
		<div class="form-group">
			<label for="LMI_PAYMENT_NO">Payment number</label>
			<?php $no = time()-1000000000;?>
			<input type="text" disabled="disabled" class="form-control" id="LMI_PAYMENT_NO"  value="<?=$no?>">
			<input type="hidden" name="LMI_PAYMENT_NO" value="<?=$no?>">
		</div>
		<div class="form-group">
			<label for="LMI_PAYMENT_DESC">Description *</label>
			<input type="text" maxlength="254" name="LMI_PAYMENT_DESC" class="form-control" id="LMI_PAYMENT_DESC"  value="">
		</div>
		<div class="form-group">
			<label for="LMI_PAYER_PHONE_NUMBER">Phone</label>
			<input type="number"  maxlength="12" name="LMI_PAYER_PHONE_NUMBER" class="form-control" id="LMI_PAYER_PHONE_NUMBER"  placeholder="380XXXXXXXXX">
		</div>
		<div class="form-group">
			<label for="LMI_PAYER_EMAIL">Email</label>
			<input type="text" maxlength="254" name="LMI_PAYER_EMAIL" class="form-control" id="LMI_PAYER_EMAIL"  value="">
		</div>

		<button class="btn btn-default" type="submit">Submit</button>
	</form>
</div>