<div class="col-md-4">
	<form method="post" action="">

		<div class="form-group">
			<label for="LMI_SYS_PAYMENT_NO">Paymaster Id</label>
			<input type="number" class="form-control" name="LMI_SYS_PAYMENT_NO" id="LMI_SYS_PAYMENT_NO" >
		</div>

		<button class="btn btn-default" type="submit">Submit</button>
	</form>
</div>
<div class="col-md-4">
	<?php if($this->info) d($this->info, false);?>
</div>