<div class="col-md-4">
	<form method="post" action="">
		<div class="form-group">
			<label for="LMI_PAYMENT_NO">ID</label>
			<input type="number" class="form-control" name="LMI_PAYMENT_NO" id="LMI_PAYMENT_NO" >
		</div>
		<div class="form-group">
			<label for="LMI_SYS_PAYMENT_ID">Paymaster ID</label>
			<input type="number" class="form-control" name="LMI_SYS_PAYMENT_ID" id="LMI_SYS_PAYMENT_ID" >
		</div>

		<button class="btn btn-default" type="submit">Submit</button>
	</form>
</div>
<div class="col-md-4">
	<?php if($this->info) d($this->info, false);?>
</div>