<div class="col-md-4">
	<form method="post" action="<?=$this->url?>">
		<?php foreach($this->params as $k=>$v){?>
			<input type="hidden" value="<?=$v?>" name="<?=$k?>" />
		<?php }?>
		<table class="table table-striped">
			<tr>
				<td>Amount</td>
				<td><?=$this->params['LMI_PAYMENT_AMOUNT']?></td>
			</tr>

			<tr>
				<td>Payment number</td>
				<td><?=$this->params['LMI_PAYMENT_NO']?></td>
			</tr>

			<tr>
				<td>Description</td>
				<td><?=$this->params['LMI_PAYMENT_DESC']?></td>
			</tr>

			<tr>
				<td>Phone</td>
				<td><?=$this->params['LMI_PAYER_PHONE_NUMBER']?></td>
			</tr>

			<tr>
				<td>Email</td>
				<td><?=$this->params['LMI_PAYER_EMAIL']?></td>
			</tr>
		</table>
		<button class="btn btn-default" type="submit">Submit</button>
	</form>
</div>