<div class="jarviswidget">
	<header>
		<a class="btn btn-success" style="float: right;" href="/admin/upload/"><i class="fa fa-plus"></i> Загрузить
			файлы</i></a>
	</header>
	<div>
		<div class="widget-body no-padding">

			<div class="widget-body-toolbar">

			</div>

			<table id="dt_basic" class="table table-striped table-bordered table-hover">
				<thead>
				<tr>
					<th></th>
					<th>Название</th>
					<th>Тип</th>
					<th>Путь</th>
					<th>Размер</th>
					<th>Дата</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach ($this->files as $file) { ?>
					<tr>
						<td>
							<a class="btn btn-default btn-circle" title="Редактировать"
							   href="/admin/editfile/id/<?= $file->getId() ?>">
								<i class="glyphicon glyphicon-pencil"></i>
							</a>
							<a class="btn btn-default btn-circle" title="Просмотреть"
							   target="_blank"
							   href="<?= $file->getLocation() ?>">
								<i class="glyphicon glyphicon-eye-open"></i>
							</a>
							<a class="btn btn-warning btn-circle" title="Удалить"
							   href="/admin/delfile/id/<?= $file->getId() ?>"
							   onclick="return confirm('Вы уверены что хотите удалить ?')">
								<i class="glyphicon glyphicon-remove"></i>
							</a>

						</td>
						<td><?= $file->getName() ?></td>
						<td><?= $file->getHeaderType() ?></td>
						<td><?= $file->getLocation() ?></td>
						<td><?= $file->SizeText() ?></td>
						<td><?= date('d-m-Y H:i:s', strtotime($file->getCtime())); ?></td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>


<script src="/admin_template/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ColReorder.min.js"></script>
<script src="/admin_template/js/plugin/datatables/FixedColumns.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ColVis.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ZeroClipboard.js"></script>
<script src="/admin_template/js/plugin/datatables/media/js/TableTools.min.js"></script>
<script src="/admin_template/js/plugin/datatables/DT_bootstrap.js"></script>

<script type="text/javascript">
	$(document).ready(function () {

		$('#dt_basic').dataTable({
			"sPaginationType": "bootstrap_full"
		});

	});
</script>