<div class="jarviswidget">
	<header>
	</header>
	<div class="widget-body">
		<form method="post" action="" enctype="multipart/form-data" autocomplete="off">

			<div class="form-group <?php if (isset($this->errors['Name'])) echo 'has-error'; ?>">
				<label class="col-md-2 control-label">Название *</label>

				<div class="col-md-10">
					<input type="text" value="<?= $this->item->getName() ?>" name="Name"
						   class="form-control">
				</div>
				<div class="clearfix"></div>
			</div>

			<div class="form-group <?php if(isset($this->errors['TypeId'])) echo 'has-error';?>">
				<label class="col-md-2 control-label">Тип</label>

				<div class="col-md-10">
					<select name="TypeId" class="form-control">
						<?php foreach (Models_Gallery::$types as $k => $v) { ?>
							<option
								value="<?= $k ?>" <?php if ($k == $this->item->getTypeId()) echo 'selected="selected"' ?>><?= $v ?></option>
						<?php } ?>
					</select>
				</div>
				<div class="clearfix"></div>
			</div>

			<div class="form-group">
				<label class="col-md-2 control-label">Описание</label>

				<div class="col-md-10">
					<textarea name="Description" class="TinyMCE"><?= $this->item->getDescription() ?></textarea>
				</div>
				<div class="clearfix"></div>
			</div>

			<div class="form-actions">
				<div class="row">
					<div class="col-md-12">
						<a href="/admin/" type="reset" class="btn btn-default">
							Отмена
						</a>
						<button type="submit" class="btn btn-primary">
							<i class="fa fa-save"></i>
							Сохранить
						</button>
					</div>
				</div>
			</div>

		</form>
	</div>
</div>

<div class="jarviswidget">
	<header>
		<a class="btn btn-success" style="float: right;" href="/admin/upload/gallery/<?=$this->item->getId()?>"><i class="fa fa-plus"></i> Загрузить
			файлы</i></a>
	</header>
	<div>
		<div class="widget-body no-padding">

			<div class="widget-body-toolbar">

			</div>

			<table id="dt_basic" class="table table-striped table-bordered table-hover">
				<thead>
				<tr>
					<th></th>
					<th>Название</th>
					<th>Тип</th>
					<th>Путь</th>
					<th>Изображение</th>
					<th>Размер</th>
					<th>Дата</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach ($this->item->getItems() as $file) { ?>
					<tr>
						<td>
							<a class="btn btn-default btn-circle" title="Редактировать"
							   href="/admin/editfile/id/<?= $file->getId() ?>">
								<i class="glyphicon glyphicon-pencil"></i>
							</a>
							<a class="btn btn-default btn-circle" title="Просмотреть"
							   target="_blank"
							   href="<?= $file->getLocation() ?>">
								<i class="glyphicon glyphicon-eye-open"></i>
							</a>
							<a class="btn btn-warning btn-circle" title="Удалить"
							   href="/admin/delfile/id/<?= $file->getId() ?>"
							   onclick="return confirm('Вы уверены что хотите удалить ?')">
								<i class="glyphicon glyphicon-remove"></i>
							</a>

						</td>
						<td><?= $file->getName() ?></td>
						<td><?= $file->getHeaderType() ?></td>
						<td><?= $file->getLocation() ?></td>
						<td><?php if($file->getTypeId() == 1){ ?>
								<img src="<?= $file->getSmallImage() ?>" style="max-height: 60px; max-width: 60px;" alt="<?= $file->getName() ?>" />
						<?php }?>
						</td>
						<td><?= $file->SizeText() ?></td>
						<td><?= date('d-m-Y H:i:s', strtotime($file->getCtime())); ?></td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>


<script src="/admin_template/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ColReorder.min.js"></script>
<script src="/admin_template/js/plugin/datatables/FixedColumns.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ColVis.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ZeroClipboard.js"></script>
<script src="/admin_template/js/plugin/datatables/media/js/TableTools.min.js"></script>
<script src="/admin_template/js/plugin/datatables/DT_bootstrap.js"></script>

<script type="text/javascript">
	$(document).ready(function () {

		$('#dt_basic').dataTable({
			"sPaginationType": "bootstrap_full"
		});

	});
</script>