<div class="jarviswidget">
	<header>
		<a class="btn btn-success" style="float: right;" href="/admin/user/"><i class="fa fa-plus"></i> Новый пользователь</i></a>
	</header>
	<div>
		<div class="widget-body no-padding">

			<div class="widget-body-toolbar">

			</div>

			<table id="dt_basic" class="table table-striped table-bordered table-hover">
				<thead>
				<tr>
					<th></th>
					<th>ID</th>
					<th>Статус</th>
					<th>Тип</th>
					<th>Логин</th>
					<th>ФИО</th>
					<th>Email</th>
					<th>Тел.</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach ($this->users as $user ) {?>
					<tr>
						<td>
							<a class="btn btn-default btn-circle" title="Редактировать" href="/admin/user/id/<?=$user->getId()?>">
								<i class="glyphicon glyphicon-pencil"></i>
							</a>
							<a class="btn btn-warning btn-circle" title="Удалить" href="/admin/users/delete/<?=$user->getId()?>"
								 onclick="return confirm('Вы уверены что хотите удалить ?')">
								<i class="glyphicon glyphicon-remove"></i>
							</a>

						</td>
						<td><?=$user->getId()?></td>
						<td><?=$user->getAllStatus()?></td>
						<td><?=$user->getType()?></td>
						<td><?=$user->getUsername()?></td>
						<td><?=$user->getFullname()?></td>
						<td><?=$user->getEmail()?></td>
						<td><?=$user->getPhone()?></td>
					</tr>

				<?php }	?>
				</tbody>
			</table>

		</div>
	</div>
</div>


<script src="/admin_template/js/plugin/datatables/jquery.dataTables-cust.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ColReorder.min.js"></script>
<script src="/admin_template/js/plugin/datatables/FixedColumns.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ColVis.min.js"></script>
<script src="/admin_template/js/plugin/datatables/ZeroClipboard.js"></script>
<script src="/admin_template/js/plugin/datatables/media/js/TableTools.min.js"></script>
<script src="/admin_template/js/plugin/datatables/DT_bootstrap.js"></script>

<script type="text/javascript">
	$(document).ready(function () {

		$('#dt_basic').dataTable({
			"sPaginationType": "bootstrap_full"
		});

	});
</script>