<div class="row">

	<div class="col-sm-12 col-md-12 col-lg-3">
		<!-- new widget -->
		<div class="jarviswidget jarviswidget-color-blueDark">
			<header>
				<h2> Добавить событие </h2>
			</header>

			<!-- widget div-->
			<div>

				<div class="widget-body">
					<!-- content goes here -->

					<form id="add-event-form">
						<fieldset>

							<div class="form-group">
								<label>Выберите иконку</label>

								<div class="btn-group btn-group-sm btn-group-justified" data-toggle="buttons">
									<label class="btn btn-default active">
										<input type="radio" name="iconselect" id="icon-1" value="fa-info" checked>
										<i class="fa fa-info text-muted"></i> </label>
									<label class="btn btn-default">
										<input type="radio" name="iconselect" id="icon-2" value="fa-warning">
										<i class="fa fa-warning text-muted"></i> </label>
									<label class="btn btn-default">
										<input type="radio" name="iconselect" id="icon-3" value="fa-check">
										<i class="fa fa-check text-muted"></i> </label>
									<label class="btn btn-default">
										<input type="radio" name="iconselect" id="icon-4" value="fa-user">
										<i class="fa fa-user text-muted"></i> </label>
									<label class="btn btn-default">
										<input type="radio" name="iconselect" id="icon-5" value="fa-lock">
										<i class="fa fa-lock text-muted"></i> </label>
									<label class="btn btn-default">
										<input type="radio" name="iconselect" id="icon-6" value="fa-clock-o">
										<i class="fa fa-clock-o text-muted"></i> </label>
								</div>
							</div>

							<div class="form-group">
								<label>Название</label>
								<input class="form-control" id="title" name="title" maxlength="40" type="text"
									   placeholder="">
							</div>
							<div class="form-group">
								<label>описание</label>
								<textarea class="form-control" placeholder="" rows="3" maxlength="40"
										  id="description"></textarea>
							</div>

							<div class="form-group">
								<label>Выберите цвет</label>

								<div class="btn-group btn-group-justified btn-select-tick" data-toggle="buttons">
									<label class="btn bg-color-darken active">
										<input type="radio" name="priority" id="option1"
											   value="bg-color-darken txt-color-white" checked>
										<i class="fa fa-check txt-color-white"></i> </label>
									<label class="btn bg-color-blue">
										<input type="radio" name="priority" id="option2"
											   value="bg-color-blue txt-color-white">
										<i class="fa fa-check txt-color-white"></i> </label>
									<label class="btn bg-color-orange">
										<input type="radio" name="priority" id="option3"
											   value="bg-color-orange txt-color-white">
										<i class="fa fa-check txt-color-white"></i> </label>
									<label class="btn bg-color-greenLight">
										<input type="radio" name="priority" id="option4"
											   value="bg-color-greenLight txt-color-white">
										<i class="fa fa-check txt-color-white"></i> </label>
									<label class="btn bg-color-blueLight">
										<input type="radio" name="priority" id="option5"
											   value="bg-color-blueLight txt-color-white">
										<i class="fa fa-check txt-color-white"></i> </label>
									<label class="btn bg-color-red">
										<input type="radio" name="priority" id="option6"
											   value="bg-color-red txt-color-white">
										<i class="fa fa-check txt-color-white"></i> </label>
								</div>
							</div>

						</fieldset>
						<div class="form-actions">
							<div class="row">
								<div class="col-md-12">
									<button class="btn btn-default" type="button" id="add-event">
										Добавить
									</button>
								</div>
							</div>
						</div>
					</form>

					<!-- end content -->
				</div>

			</div>
			<!-- end widget div -->
		</div>
		<!-- end widget -->

		<div class="well well-sm" id="event-container">
			<form>
				<fieldset>
					<legend>
						Перетащите событие на календарь
					</legend>
					<ul id='external-events' class="list-unstyled">
						<?php foreach ($this->noActivEvents as $event) { ?>
							<li>
								<span class="<?= $event->getClasses() ?>"
									  data-description="<?= $event->getDescription() ?>"
									  data-icon="<?= $event->getIcon() ?>">
									<i class="calendar-remove fa fa-times-circle" onclick="EventRemove($(this))"
									   rel="<?= $event->getId() ?>"></i>
									<?= $event->getTitle() ?>
								</span>
							</li>
						<?php } ?>
					</ul>

					<div class="checkbox">
						<label>
							<input type="checkbox" id="drop-remove" class="checkbox style-0">
							<span>Удалить событие (выберите и нажмите на событие в календаре для удаления)</span> </label>

					</div>
				</fieldset>
			</form>

		</div>
	</div>
	<div class="col-sm-12 col-md-12 col-lg-9">

		<!-- new widget -->
		<div class="jarviswidget jarviswidget-color-blueDark">

			<!-- widget options:
			usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

			data-widget-colorbutton="false"
			data-widget-editbutton="false"
			data-widget-togglebutton="false"
			data-widget-deletebutton="false"
			data-widget-fullscreenbutton="false"
			data-widget-custombutton="false"
			data-widget-collapsed="true"
			data-widget-sortable="false"

			-->
			<header>
				<span class="widget-icon"> <i class="fa fa-calendar"></i> </span>

				<h2> События </h2>

				<div class="widget-toolbar">
					<!-- add: non-hidden - to disable auto hide -->
					<div class="btn-group">
						<button class="btn dropdown-toggle btn-xs btn-default" data-toggle="dropdown">
							Показать <i class="fa fa-caret-down"></i>
						</button>
						<ul class="dropdown-menu js-status-update pull-right">
							<li>
								<a href="javascript:void(0);" id="mt">Месяц</a>
							</li>
							<li>
								<a href="javascript:void(0);" id="ag">День</a>
							</li>
							<li>
								<a href="javascript:void(0);" id="td">Сегодня</a>
							</li>
						</ul>
					</div>
				</div>
			</header>

			<!-- widget div-->
			<div>

				<div class="widget-body no-padding">
					<!-- content goes here -->
					<div class="widget-body-toolbar">

						<div id="calendar-buttons">

							<div class="btn-group">
								<a href="javascript:void(0)" class="btn btn-default btn-xs" id="btn-prev"><i
										class="fa fa-chevron-left"></i></a>
								<a href="javascript:void(0)" class="btn btn-default btn-xs" id="btn-next"><i
										class="fa fa-chevron-right"></i></a>
							</div>
						</div>
					</div>
					<div id="calendar"></div>

					<!-- end content -->
				</div>

			</div>
			<!-- end widget div -->
		</div>
		<!-- end widget -->

	</div>

</div>


<script src="js/plugin/fullcalendar/jquery.fullcalendar.min.js"></script>
<script type="text/javascript">

	function EventRemove(obj) {
		$.ajax({
			type: "POST",
			url: "/admin/calendar/act/del",
			dataType: 'json',
			data: 'id=' + obj.attr('rel'),
			success: function (msg) {
				obj.parents('li').remove();
			}
		});
	}

	$(document).ready(function () {
		"use strict";

		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();

		var hdr = {
			left: 'title',
			center: 'month,agendaWeek,agendaDay',
			right: 'prev,today,next'
		};

		var initDrag = function (e) {
			// create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
			// it doesn't need to have a start or end

			var eventObject = {
				title: $.trim(e.children().text()), // use the element's text as the event title
				description: $.trim(e.children('span').attr('data-description')),
				icon: $.trim(e.children('span').attr('data-icon')),
				id: $.trim(e.children('span').children('.calendar-remove').attr('rel')),
				className: $.trim(e.children('span').attr('class')) // use the element's children as the event class
			};
			// store the Event Object in the DOM element so we can get to it later
			e.data('eventObject', eventObject);

			// make the event draggable using jQuery UI
			e.draggable({
				zIndex: 999,
				revert: true, // will cause the event to go back to its
				revertDuration: 0 //  original position after the drag
			});
		};

		var addEvent = function (title, priority, description, icon) {


			$.ajax({
				type: "POST",
				url: "/admin/calendar/act/add",
				dataType: 'json',
				data: 'title=' + title + '&priority=' + priority + '&description=' + description + '&icon=' + icon,
				success: function (msg) {
					if (msg.id) {
						title = title.length === 0 ? "Untitled Event" : title;
						description = description.length === 0 ? "No Description" : description;
						icon = icon.length === 0 ? " " : icon;
						priority = priority.length === 0 ? "label label-default" : priority;

						var html = $('<li>' +
							'<span class="' + priority + '" data-description="' + description + '" data-icon="' +
							icon + '">' + '<i class="calendar-remove fa fa-times-circle" onclick="EventRemove($(this))" rel="' + msg.id + '"></i>'
							+ title + '</span>' +
							'</li>').prependTo('ul#external-events').hide().fadeIn();

						$("#event-container").effect("highlight", 800);
						initDrag(html);
					}
				}
			});


		};

		/* initialize the external events
		 -----------------------------------------------------------------*/

		$('#external-events > li').each(function () {
			initDrag($(this));
		});

		$('#add-event').click(function () {
			var title = $('#title').val(),
				priority = $('input:radio[name=priority]:checked').val(),
				description = $('#description').val(),
				icon = $('input:radio[name=iconselect]:checked').val();

			addEvent(title, priority, description, icon);
		});

		/* initialize the calendar
		 -----------------------------------------------------------------*/

		$('#calendar').fullCalendar({

			header: hdr,
			buttonText: {
				prev: '<i class="fa fa-chevron-left"></i>',
				next: '<i class="fa fa-chevron-right"></i>'
			},

			editable: true,
			droppable: true, // this allows things to be dropped onto the calendar !!!

			drop: function (date, allDay) { // this function is called when something is dropped
				// retrieve the dropped element's stored Event Object
				var originalEventObject = $(this).data('eventObject');

				// we need to copy it, so that multiple events don't have a reference to the same object
				var copiedEventObject = $.extend({}, originalEventObject);

				// assign it the date that was reported
				copiedEventObject.start = date;
				copiedEventObject.allDay = allDay;
				$.ajax({
					type: "POST",
					url: "/admin/calendar/act/dates",
					dataType: 'json',
					data: {id: copiedEventObject.id, start: copiedEventObject.start, allday: copiedEventObject.allDay},
					success: function (msg) {
					}
				});

				// render the event on the calendar
				// the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
				$('#calendar').fullCalendar('renderEvent', copiedEventObject, true);


				$(this).remove();
			},

			select: function (start, end, allDay) {
				var title = prompt('Event Title:');
				if (title) {
					calendar.fullCalendar('renderEvent', {
							title: title,
							start: start,
							end: end,
							allDay: allDay
						}, true // make the event "stick"
					);
				}
				calendar.fullCalendar('unselect');
			},

			events: [
				<?php foreach($this->ActivEvents as $event){?>
				{
					title: '<?=$event->getTitle()?>',
					start: new Date(<?=strtotime($event->getStart())*1000?>),
					<?php if($event->getEnd()){?>
					end:  new Date(<?=strtotime($event->getEnd())*1000?>),
					<?php }?>
					description: '<?=$event->getDescription()?>',
					allDay: <?=(int)$event->getIsAllDay()?>,
					id: <?=$event->getId()?>,
					className: ["event", "<?=$event->getClasses()?>"],
					icon: '<?=$event->getIcon()?>'
				},
				<?php }?>
			],

			eventRender: function (event, element, icon) {
				if (!event.description == "") {
					element.find('.fc-event-title').append("<br/><span class='ultra-light'>" + event.description +
						"</span>");
				}
				if (!event.icon == "") {
					element.find('.fc-event-title').append("<i class='air air-top-right fa " + event.icon +
						" '></i>");
				}
			}
			,
			eventDrop: function (event, jsEvent, ui, view) {
				$.ajax({
					type: "POST",
					url: "/admin/calendar/act/dates",
					dataType: 'json',
					data: {id: event.id, start: event.start, allday: event.allDay, end: event.end},
					success: function (msg) {
					}
				});
			}
			,
			eventResize: function (event, jsEvent, ui, view) {
				$.ajax({
					type: "POST",
					url: "/admin/calendar/act/dates",
					dataType: 'json',
					data: {id: event.id, start: event.start, allday: event.allDay, end: event.end},
					success: function (msg) {
					}
				});
			},
			eventClick: function(event, jsEvent, view){
				if($('#drop-remove').prop('checked')){
					if(confirm('Удалить событие ?')){
						$.ajax({
							type: "POST",
							url: "/admin/calendar/act/del",
							dataType: 'json',
							data: {id: event.id},
							success: function (msg) {
								$('#calendar').fullCalendar('removeEvents',event.id);
							}
						});
					}
				}
			},

			windowResize: function (event, ui) {
				$('#calendar').fullCalendar('render');
			},

			monthNames: ['Январь','Февраль','Март','Апрель','Май','οюнь','οюль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
			monthNamesShort: ['Янв.','Фев.','Март','Апр.','Май','οюнь','οюль','Авг.','Сент.','Окт.','Ноя.','Дек.'],
			dayNames: ["Воскресенье","Понедельник","Вторник","Среда","Четверг","Пятница","Суббота"],
			dayNamesShort: ["ВС","ПН","ВТ","СР","ЧТ","ПТ","СБ"],
			firstDay: 1,
			width: 750
		})
		;

		/* hide default buttons */
		$('.fc-header-right, .fc-header-center').hide();


		$('#calendar-buttons #btn-prev').click(function () {
			$('.fc-button-prev').click();
			return false;
		});

		$('#calendar-buttons #btn-next').click(function () {
			$('.fc-button-next').click();
			return false;
		});

		$('#calendar-buttons #btn-today').click(function () {
			$('.fc-button-today').click();
			return false;
		});

		$('#mt').click(function () {
			$('#calendar').fullCalendar('changeView', 'month');
		});

		$('#ag').click(function () {
			$('#calendar').fullCalendar('changeView', 'agendaWeek');
		});

		$('#td').click(function () {
			$('#calendar').fullCalendar('changeView', 'agendaDay');
		});
	})

</script>