<link rel="stylesheet" type="text/css" href="/admin_template/js/plugin/elfinder-2.x/css/elfinder.min.css">
<link rel="stylesheet" type="text/css" href="/admin_template/js/plugin/elfinder-2.x/css/theme.css">

<!-- elFinder JS (REQUIRED) -->
<script src="/admin_template/js/plugin/elfinder-2.x/js/elfinder.min.js"></script>

<!-- elFinder translation (OPTIONAL) -->
<script src="/admin_template/js/plugin/elfinder-2.x/js/i18n/elfinder.ru.js"></script>

<!-- elFinder initialization (REQUIRED) -->
<script type="text/javascript" charset="utf-8">
	// Documentation for client options:
	// https://github.com/Studio-42/elFinder/wiki/Client-configuration-options
	$(document).ready(function() {
		$('#elfinder').elfinder({
			url : '/admin/filesystemconnector'  // connector URL (REQUIRED)
			, lang: 'ru'                    // language (OPTIONAL)
		});
	});
</script>

<div id="elfinder"></div>